apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  type: NodePort
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 8080          # 서비스가 노출할 포트
      targetPort: 8080    # 컨테이너의 포트
      nodePort: 30080     # 외부에서 접근할 NodePort (30080은 예시입니다)
